language: c
sudo: true

before_install:
  - sudo apt-get install valgrind cppcheck
  - git clone https://github.com/Snaipe/Criterion.git
  - cd Criterion && mkdir build && cd build
  - CC=gcc cmake ..
  - CC=gcc cmake --build .
  - sudo make install
  - cd ../../

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8']
      env: COMPILER=gcc-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9']
      env: COMPILER=gcc-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMPILER=gcc-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6']
      env: COMPILER=gcc-6

    - os: linux
      compiler: clang
      env: COMPILER=clang

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: ['clang-3.6']
      env: COMPILER=clang-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']
      env: COMPILER=clang-3.7

script:
  - uname -a
  - $COMPILER --version
  - CC=$COMPILER cmake . && make
  - cppcheck --verbose ./src
  - cd tests
  - cmake . && make
  - ./xstarter_tests --verbose=1
  - valgrind --leak-check=full ./xstarter_tests --no-early-exit --verbose=1
